# These are supported funding model platforms

github: owenthereal
open_collective: owenthereal
custom: https://www.paypal.com/donate/?business=6ELMGR7GQYAU6&amount=20&no_recurring=0&item_name=Buy+me+a+coffee&currency_code=USD
